#include "bgfxrenderer.h"

#include <bgfx/bgfx.h>
#include <bgfx/platform.h>
#include <bx/math.h>
#include <cstring>
#include <cmath>

// Embedded compiled shaders (generated by shaderc → xxd)
#include "../shaders/vs_basic_metal.h"
#include "../shaders/fs_basic_metal.h"

namespace qlcrender {

static bgfx::ShaderHandle loadEmbeddedShader(const uint8_t* data, uint32_t size)
{
    const bgfx::Memory* mem = bgfx::copy(data, size);
    return bgfx::createShader(mem);
}

BgfxRenderer::BgfxRenderer()
{
}

BgfxRenderer::~BgfxRenderer()
{
    if (m_initialized)
        shutdown();
}

bool BgfxRenderer::init(void* nativeWindowHandle, uint32_t width, uint32_t height)
{
    if (m_initialized)
        return false;

    m_width = width;
    m_height = height;

    // Single-threaded mode: call renderFrame() before init() on macOS Metal
    bgfx::renderFrame();

    bgfx::Init init;
#if BX_PLATFORM_OSX
    init.type = bgfx::RendererType::Metal;
#else
    init.type = bgfx::RendererType::Count;  // auto-detect
#endif
    init.platformData.nwh = nativeWindowHandle;
    init.resolution.width = width;
    init.resolution.height = height;
    init.resolution.reset = BGFX_RESET_VSYNC;

    if (!bgfx::init(init))
        return false;

    fprintf(stderr, "[BgfxRenderer] Initialized: renderer=%s, %dx%d\n",
            bgfx::getRendererName(bgfx::getRendererType()), width, height);

    // Dark gray background
    bgfx::setViewClear(0, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH,
                        0x1a1a1aff, 1.0f, 0);
    bgfx::setViewRect(0, 0, 0, uint16_t(width), uint16_t(height));

    // Initialize vertex layouts
    PosColorVertex::init();
    PosVertex::init();

    // Create cube mesh
    createCubeMesh(m_cubeVbh, m_cubeIbh);

    // Load embedded shaders and create program
    bgfx::ShaderHandle vsh = loadEmbeddedShader(vs_basic_metal_bin, sizeof(vs_basic_metal_bin));
    bgfx::ShaderHandle fsh = loadEmbeddedShader(fs_basic_metal_bin, sizeof(fs_basic_metal_bin));
    if (!bgfx::isValid(vsh))
        fprintf(stderr, "[BgfxRenderer] Failed to create vertex shader\n");
    if (!bgfx::isValid(fsh))
        fprintf(stderr, "[BgfxRenderer] Failed to create fragment shader\n");
    m_colorProgram = bgfx::createProgram(vsh, fsh, true);
    if (!bgfx::isValid(m_colorProgram))
        fprintf(stderr, "[BgfxRenderer] Failed to create shader program\n");
    else
        fprintf(stderr, "[BgfxRenderer] Shader program created OK\n");

    // Create color uniform
    m_u_color = bgfx::createUniform("u_color", bgfx::UniformType::Vec4);

    // Enable debug text for initial verification
    bgfx::setDebug(BGFX_DEBUG_TEXT);

    m_initialized = true;
    return true;
}

void BgfxRenderer::shutdown()
{
    if (!m_initialized)
        return;

    m_meshLoader.shutdown();
    destroyCubeMesh(m_cubeVbh, m_cubeIbh);

    if (bgfx::isValid(m_colorProgram))
        bgfx::destroy(m_colorProgram);
    if (bgfx::isValid(m_u_color))
        bgfx::destroy(m_u_color);

    bgfx::shutdown();
    m_initialized = false;
}

void BgfxRenderer::resize(uint32_t width, uint32_t height)
{
    if (!m_initialized || (width == m_width && height == m_height))
        return;

    m_width = width;
    m_height = height;
    bgfx::reset(width, height, BGFX_RESET_VSYNC);
    bgfx::setViewRect(0, 0, 0, uint16_t(width), uint16_t(height));
}

void BgfxRenderer::frame()
{
    if (!m_initialized || m_width == 0 || m_height == 0)
        return;

    // Set view 0 clear and rect every frame (must be set before touch/submit)
    bgfx::setViewRect(0, 0, 0, uint16_t(m_width), uint16_t(m_height));
    bgfx::setViewClear(0, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH,
                        0x303030ff, 1.0f, 0);
    bgfx::setViewMode(0, bgfx::ViewMode::Sequential);

    // Touch view 0 to ensure it's rendered even with no draw calls
    bgfx::touch(0);

    // Camera
    float view[16];
    float proj[16];
    m_camera.viewMatrix(view);
    float aspect = float(m_width) / float(m_height);
    m_camera.projMatrix(proj, aspect, bgfx::getCaps()->homogeneousDepth);
    bgfx::setViewTransform(0, view, proj);

    // Debug text
    bgfx::dbgTextClear();
    bgfx::dbgTextPrintf(1, 1, 0x0f, "QLC+ Spatial View (bgfx)");
    bgfx::dbgTextPrintf(1, 2, 0x07, "Fixtures: %d  Yaw: %.0f  Pitch: %.0f  Dist: %.1f",
                         (int)m_fixtures.size(), m_camera.yaw(), m_camera.pitch(), m_camera.distance());

    renderGrid();
    renderFixtures();

    bgfx::frame();
}

// --- Camera ---

void BgfxRenderer::setCameraOrbit(float yaw, float pitch, float distance)
{
    m_camera.setOrbit(yaw, pitch, distance);
}

void BgfxRenderer::setCameraTarget(float x, float y, float z)
{
    m_camera.setTarget(x, y, z);
}

void BgfxRenderer::panCamera(float dx, float dy)
{
    m_camera.pan(dx, dy);
}

// --- Scene data ---

void BgfxRenderer::setFixtures(const std::vector<RenderFixture>& fixtures)
{
    m_fixtures = fixtures;
}

// --- Private rendering ---

void BgfxRenderer::renderGrid()
{
    // Grid on XY plane (Z=0) using transient line geometry
    // Axis lines + grid lines. Will work even without a shader program
    // by using bgfx's built-in vertex color rendering.
    const float extent = 10.0f;
    const float step = 1.0f;
    const int gridLines = int(extent / step) * 2 + 1;
    // 3 axis lines (6 verts) + grid lines (gridLines * 2 directions * 2 verts)
    const uint32_t axisVerts = 6;
    const uint32_t gridVerts = uint32_t(gridLines * 2 * 2);
    const uint32_t totalVerts = axisVerts + gridVerts;

    if (!bgfx::getAvailTransientVertexBuffer(totalVerts, PosColorVertex::layout))
        return;

    bgfx::TransientVertexBuffer tvb;
    bgfx::allocTransientVertexBuffer(&tvb, totalVerts, PosColorVertex::layout);
    auto* v = (PosColorVertex*)tvb.data;
    uint32_t idx = 0;

    // Axis lines
    v[idx++] = { -extent, 0, 0, 0xff0000ff };  // X axis red (ABGR)
    v[idx++] = {  extent, 0, 0, 0xff0000ff };
    v[idx++] = { 0, -extent, 0, 0xff00ff00 };  // Y axis green
    v[idx++] = { 0,  extent, 0, 0xff00ff00 };
    v[idx++] = { 0, 0, 0, 0xffff0000 };        // Z axis blue (up)
    v[idx++] = { 0, 0, 5, 0xffff0000 };

    // Grid lines
    const uint32_t lineColor = 0xff404040;
    for (float g = -extent; g <= extent + 0.001f; g += step)
    {
        v[idx++] = { -extent, g, 0, lineColor };
        v[idx++] = {  extent, g, 0, lineColor };
        v[idx++] = { g, -extent, 0, lineColor };
        v[idx++] = { g,  extent, 0, lineColor };
    }

    float identity[16];
    bx::mtxIdentity(identity);
    bgfx::setTransform(identity);
    bgfx::setState(BGFX_STATE_WRITE_RGB | BGFX_STATE_PT_LINES);
    bgfx::setVertexBuffer(0, &tvb);

    if (bgfx::isValid(m_colorProgram))
        bgfx::submit(0, m_colorProgram);
    else
        bgfx::discard();
}

void BgfxRenderer::renderFixtures()
{
    for (const auto& fixture : m_fixtures)
    {
        // Try to load the proper 3D mesh for this fixture type
        const LoadedMesh *mesh = nullptr;
        const char *meshFile = MeshLoader::meshFileForFixtureType(fixture.fixtureType);
        if (meshFile && !m_meshBasePath.empty())
        {
            std::string fullPath = m_meshBasePath + meshFile;
            mesh = m_meshLoader.getMesh(fullPath);
        }

        if (mesh && mesh->isValid())
        {
            // Render with the 3D model mesh (already at correct scale from .dae)
            bgfx::setTransform(fixture.transform);
            bgfx::setVertexBuffer(0, mesh->vbh);
            bgfx::setIndexBuffer(mesh->ibh);
        }
        else if (bgfx::isValid(m_cubeVbh) && bgfx::isValid(m_cubeIbh))
        {
            // Fallback: 0.2m cube
            float scale[16];
            bx::mtxScale(scale, 0.2f);
            float model[16];
            bx::mtxMul(model, scale, fixture.transform);

            bgfx::setTransform(model);
            bgfx::setVertexBuffer(0, m_cubeVbh);
            bgfx::setIndexBuffer(m_cubeIbh);
        }
        else
        {
            continue;
        }

        bgfx::setState(BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A
                        | BGFX_STATE_WRITE_Z | BGFX_STATE_DEPTH_TEST_LESS);

        if (bgfx::isValid(m_colorProgram))
            bgfx::submit(0, m_colorProgram);
        else
            bgfx::discard();
    }
}

// --- Factory ---

SpatialRenderer *createBgfxRenderer()
{
    return new BgfxRenderer();
}

} // namespace qlcrender
