#include "bgfxrenderer.h"

#include <bgfx/bgfx.h>
#include <bgfx/platform.h>
#include <bx/math.h>
#include <cstring>
#include <cmath>

// Embedded compiled shaders (generated by shaderc → xxd)
#include "../shaders/vs_basic_metal.h"
#include "../shaders/fs_basic_metal.h"
#include "../shaders/vs_lit_metal.h"
#include "../shaders/fs_lit_metal.h"

namespace qlcrender {

// ---------------------------------------------------------------------------
// BgfxCallback — screenshot capture from GPU framebuffer
// ---------------------------------------------------------------------------

void BgfxCallback::screenShot(const char *, uint32_t width, uint32_t height,
                               uint32_t pitch, bgfx::TextureFormat::Enum format,
                               const void *data, uint32_t size, bool yflip)
{
    // Convert raw BGRA/RGBA pixel data to PNG in memory
    // bgfx typically delivers BGRA8 on Metal
    m_width = width;
    m_height = height;

    // Build raw RGBA image (swap B/R if BGRA)
    bool isBGRA = (format == bgfx::TextureFormat::BGRA8);
    std::vector<uint8_t> rgba(width * height * 4);

    for (uint32_t y = 0; y < height; y++)
    {
        uint32_t srcY = yflip ? (height - 1 - y) : y;
        const uint8_t *srcRow = (const uint8_t *)data + srcY * pitch;
        uint8_t *dstRow = rgba.data() + y * width * 4;
        for (uint32_t x = 0; x < width; x++)
        {
            if (isBGRA)
            {
                dstRow[x*4 + 0] = srcRow[x*4 + 2]; // R
                dstRow[x*4 + 1] = srcRow[x*4 + 1]; // G
                dstRow[x*4 + 2] = srcRow[x*4 + 0]; // B
                dstRow[x*4 + 3] = srcRow[x*4 + 3]; // A
            }
            else
            {
                memcpy(dstRow + x*4, srcRow + x*4, 4);
            }
        }
    }

    // Use stb_image_write (already available via tinygltf) — but simpler to
    // just store raw RGBA and let the caller encode. Actually, let's use
    // QImage to encode PNG since Qt is available in the qmlui layer.
    // For now, store raw RGBA and dimensions. The MCP server will convert.
    m_pngData = std::move(rgba);
    m_ready = true;
    m_requested = false;
}

bool BgfxCallback::takeScreenshot(std::vector<uint8_t> &outData, uint32_t &outW, uint32_t &outH)
{
    if (!m_ready)
        return false;
    outData = std::move(m_pngData);
    outW = m_width;
    outH = m_height;
    m_ready = false;
    return true;
}

// ---------------------------------------------------------------------------

static bgfx::ShaderHandle loadEmbeddedShader(const uint8_t* data, uint32_t size)
{
    const bgfx::Memory* mem = bgfx::copy(data, size);
    return bgfx::createShader(mem);
}

BgfxRenderer::BgfxRenderer()
{
}

BgfxRenderer::~BgfxRenderer()
{
    if (m_initialized)
        shutdown();
}

bool BgfxRenderer::init(void* nativeWindowHandle, uint32_t width, uint32_t height)
{
    if (m_initialized)
        return false;

    m_width = width;
    m_height = height;

    // Single-threaded mode: call renderFrame() before init() on macOS Metal
    bgfx::renderFrame();

    bgfx::Init init;
#if BX_PLATFORM_OSX
    init.type = bgfx::RendererType::Metal;
#else
    init.type = bgfx::RendererType::Count;  // auto-detect
#endif
    init.platformData.nwh = nativeWindowHandle;
    init.resolution.width = width;
    init.resolution.height = height;
    init.resolution.reset = BGFX_RESET_VSYNC;
    init.callback = &m_callback;

    if (!bgfx::init(init))
        return false;

    fprintf(stderr, "[BgfxRenderer] Initialized: renderer=%s, %dx%d\n",
            bgfx::getRendererName(bgfx::getRendererType()), width, height);

    // Dark gray background
    bgfx::setViewClear(0, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH,
                        0x1a1a1aff, 1.0f, 0);
    bgfx::setViewRect(0, 0, 0, uint16_t(width), uint16_t(height));

    // Initialize vertex layouts
    PosColorVertex::init();
    PosVertex::init();
    PosNormalVertex::init();

    // Create meshes
    createCubeMesh(m_cubeVbh, m_cubeIbh);
    createSphereMesh(m_sphereVbh, m_sphereIbh, 16);

    // Load embedded shaders and create program
    bgfx::ShaderHandle vsh = loadEmbeddedShader(vs_basic_metal_bin, sizeof(vs_basic_metal_bin));
    bgfx::ShaderHandle fsh = loadEmbeddedShader(fs_basic_metal_bin, sizeof(fs_basic_metal_bin));
    if (!bgfx::isValid(vsh))
        fprintf(stderr, "[BgfxRenderer] Failed to create vertex shader\n");
    if (!bgfx::isValid(fsh))
        fprintf(stderr, "[BgfxRenderer] Failed to create fragment shader\n");
    m_colorProgram = bgfx::createProgram(vsh, fsh, true);
    if (!bgfx::isValid(m_colorProgram))
        fprintf(stderr, "[BgfxRenderer] Failed to create basic shader program\n");
    else
        fprintf(stderr, "[BgfxRenderer] Basic shader program created OK\n");

    // Lit shader for fixture meshes (diffuse lighting with u_color)
    bgfx::ShaderHandle vshLit = loadEmbeddedShader(vs_lit_metal_bin, sizeof(vs_lit_metal_bin));
    bgfx::ShaderHandle fshLit = loadEmbeddedShader(fs_lit_metal_bin, sizeof(fs_lit_metal_bin));
    m_litProgram = bgfx::createProgram(vshLit, fshLit, true);
    if (!bgfx::isValid(m_litProgram))
        fprintf(stderr, "[BgfxRenderer] Failed to create lit shader program\n");
    else
        fprintf(stderr, "[BgfxRenderer] Lit shader program created OK\n");

    // Create color uniform
    m_u_color = bgfx::createUniform("u_color", bgfx::UniformType::Vec4);

    // Enable debug text for initial verification
    bgfx::setDebug(BGFX_DEBUG_TEXT);

    // Initialize GDTF primitive mesh generator
    m_primitiveGen.init();

    m_initialized = true;
    return true;
}

void BgfxRenderer::shutdown()
{
    if (!m_initialized)
        return;

    m_meshLoader.shutdown();
    m_primitiveGen.shutdown();
    destroyCubeMesh(m_cubeVbh, m_cubeIbh);
    destroySphereMesh(m_sphereVbh, m_sphereIbh);

    if (bgfx::isValid(m_colorProgram))
        bgfx::destroy(m_colorProgram);
    if (bgfx::isValid(m_litProgram))
        bgfx::destroy(m_litProgram);
    if (bgfx::isValid(m_u_color))
        bgfx::destroy(m_u_color);

    bgfx::shutdown();
    m_initialized = false;
}

void BgfxRenderer::resize(uint32_t width, uint32_t height)
{
    if (!m_initialized || (width == m_width && height == m_height))
        return;

    m_width = width;
    m_height = height;
    bgfx::reset(width, height, BGFX_RESET_VSYNC);
    bgfx::setViewRect(0, 0, 0, uint16_t(width), uint16_t(height));
}

void BgfxRenderer::frame()
{
    if (!m_initialized || m_width == 0 || m_height == 0)
        return;

    // Set view 0 clear and rect every frame (must be set before touch/submit)
    bgfx::setViewRect(0, 0, 0, uint16_t(m_width), uint16_t(m_height));
    bgfx::setViewClear(0, BGFX_CLEAR_COLOR | BGFX_CLEAR_DEPTH,
                        0x303030ff, 1.0f, 0);
    bgfx::setViewMode(0, bgfx::ViewMode::Sequential);

    // Touch view 0 to ensure it's rendered even with no draw calls
    bgfx::touch(0);

    // Camera
    float view[16];
    float proj[16];
    m_camera.viewMatrix(view);
    float aspect = float(m_width) / float(m_height);
    m_camera.projMatrix(proj, aspect, bgfx::getCaps()->homogeneousDepth);
    bgfx::setViewTransform(0, view, proj);

    // Debug text
    bgfx::dbgTextClear();
    bgfx::dbgTextPrintf(1, 1, 0x0f, "QLC+ Spatial View");
    bgfx::dbgTextPrintf(1, 2, 0x07, "Fixtures: %d  Yaw: %.0f  Pitch: %.0f  Dist: %.1f",
                         (int)m_fixtures.size(), m_camera.yaw(), m_camera.pitch(), m_camera.distance());
    // Axis legend with + markers at axis ends
    bgfx::dbgTextPrintf(1,  3, 0x04, "+X");
    bgfx::dbgTextPrintf(3,  3, 0x07, "=stage left  ");
    bgfx::dbgTextPrintf(16, 3, 0x02, "+Y");
    bgfx::dbgTextPrintf(18, 3, 0x07, "=upstage  ");
    bgfx::dbgTextPrintf(28, 3, 0x01, "+Z");
    bgfx::dbgTextPrintf(30, 3, 0x07, "=up");

    renderGrid();
    renderFixtures();
    renderEllipsoids();
    renderGizmo();

    // Handle screenshot request (fires callback during bgfx::frame)
    if (m_callback.isRequested())
    {
        bgfx::requestScreenShot(BGFX_INVALID_HANDLE, "mcp_screenshot");
    }

    bgfx::frame();
}

// --- Camera ---

void BgfxRenderer::setCameraOrbit(float yaw, float pitch, float distance)
{
    m_camera.setOrbit(yaw, pitch, distance);
}

void BgfxRenderer::setCameraTarget(float x, float y, float z)
{
    m_camera.setTarget(x, y, z);
}

void BgfxRenderer::panCamera(float dx, float dy)
{
    m_camera.pan(dx, dy);
}

bool BgfxRenderer::worldToScreen(const float worldPos[3],
                                  float &outScreenX, float &outScreenY,
                                  bool &outVisible)
{
    if (m_width == 0 || m_height == 0)
        return false;

    float view[16], proj[16];
    m_camera.viewMatrix(view);
    float aspect = float(m_width) / float(m_height);
    m_camera.projMatrix(proj, aspect, bgfx::getCaps()->homogeneousDepth);

    // Multiply: clip = proj * view * worldPos
    float vp[16];
    bx::mtxMul(vp, view, proj);

    float clip[4];
    clip[0] = vp[0]*worldPos[0] + vp[4]*worldPos[1] + vp[8]*worldPos[2]  + vp[12];
    clip[1] = vp[1]*worldPos[0] + vp[5]*worldPos[1] + vp[9]*worldPos[2]  + vp[13];
    clip[2] = vp[2]*worldPos[0] + vp[6]*worldPos[1] + vp[10]*worldPos[2] + vp[14];
    clip[3] = vp[3]*worldPos[0] + vp[7]*worldPos[1] + vp[11]*worldPos[2] + vp[15];

    if (clip[3] <= 0.0f)
    {
        outVisible = false;
        return false;
    }

    // Perspective divide → NDC
    float ndcX = clip[0] / clip[3];
    float ndcY = clip[1] / clip[3];

    // NDC → device pixels
    float deviceX = (ndcX * 0.5f + 0.5f) * float(m_width);
    float deviceY = (1.0f - (ndcY * 0.5f + 0.5f)) * float(m_height);  // flip Y

    // Device pixels → logical pixels (divide by DPR, but renderer doesn't know DPR)
    // Return device pixels — the caller divides by DPR.
    outScreenX = deviceX;
    outScreenY = deviceY;
    outVisible = (ndcX >= -1.0f && ndcX <= 1.0f && ndcY >= -1.0f && ndcY <= 1.0f);

    return true;
}

// --- Scene data ---

void BgfxRenderer::setFixtures(const std::vector<RenderFixture>& fixtures)
{
    m_fixtures = fixtures;

    // Compute local AABBs for picking
    m_localAABBs.resize(m_fixtures.size());
    for (size_t i = 0; i < m_fixtures.size(); i++)
    {
        const auto &f = m_fixtures[i];
        if (f.sceneGraph && f.sceneGraph->valid)
        {
            // Use cached AABB if already computed, otherwise compute
            if (f.sceneGraph->localAABB.valid())
                m_localAABBs[i] = f.sceneGraph->localAABB;
            else
                m_localAABBs[i] = computeSceneGraphAABB(f.sceneGraph->root);
        }
        else
        {
            m_localAABBs[i] = defaultFixtureAABB();
        }
    }
}

int32_t BgfxRenderer::hitTest(float mouseX, float mouseY,
                               uint32_t viewportW, uint32_t viewportH)
{
    float view[16], proj[16];
    m_camera.viewMatrix(view);
    float aspect = float(m_width) / float(m_height);
    m_camera.projMatrix(proj, aspect, bgfx::getCaps()->homogeneousDepth);

    HitResult hit;
    if (pickFixture(mouseX, mouseY, viewportW, viewportH,
                    view, proj, m_fixtures, m_localAABBs, hit))
    {
        return int32_t(hit.fixtureId);
    }
    return -1;
}

GizmoAxis BgfxRenderer::gizmoHitTest(float mouseX, float mouseY,
                                      uint32_t viewportW, uint32_t viewportH)
{
    if (m_selectedFixtureId < 0)
        return GizmoAxis::None;

    float view[16], proj[16];
    m_camera.viewMatrix(view);
    float aspect = float(m_width) / float(m_height);
    m_camera.projMatrix(proj, aspect, bgfx::getCaps()->homogeneousDepth);

    Ray ray = screenToRay(mouseX, mouseY, viewportW, viewportH, view, proj);
    return m_gizmo.hitTest(ray);
}

// --- Private rendering ---

void BgfxRenderer::renderGrid()
{
    // Grid on XY plane (Z=0) using transient line geometry
    // Axis lines + grid lines. Will work even without a shader program
    // by using bgfx's built-in vertex color rendering.
    const float extent = 10.0f;
    const float step = 1.0f;
    const int gridLines = int(extent / step) * 2 + 1;
    // 3 axis lines (6 verts) + 3 axis markers (12 verts) + grid lines
    const uint32_t axisVerts = 6;
    const uint32_t markerVerts = 12;
    const uint32_t gridVerts = uint32_t(gridLines * 2 * 2);
    const uint32_t totalVerts = axisVerts + markerVerts + gridVerts;

    if (!bgfx::getAvailTransientVertexBuffer(totalVerts, PosColorVertex::layout))
        return;

    bgfx::TransientVertexBuffer tvb;
    bgfx::allocTransientVertexBuffer(&tvb, totalVerts, PosColorVertex::layout);
    auto* v = (PosColorVertex*)tvb.data;
    uint32_t idx = 0;

    // Axis lines — thicker by doubling with slight offset
    const uint32_t xColor = 0xff0000ff;  // red (ABGR)
    const uint32_t yColor = 0xff00ff00;  // green
    const uint32_t zColor = 0xffff0000;  // blue

    v[idx++] = { -extent, 0, 0, xColor };  // X axis
    v[idx++] = {  extent, 0, 0, xColor };
    v[idx++] = { 0, -extent, 0, yColor };  // Y axis
    v[idx++] = { 0,  extent, 0, yColor };
    v[idx++] = { 0, 0, 0, zColor };        // Z axis (up)
    v[idx++] = { 0, 0, 5, zColor };

    // Axis endpoint markers (small cross at +X, +Y, +Z ends)
    const float m = 0.3f;  // marker size
    const float e = extent - 0.01f;
    // +X marker
    v[idx++] = { e, -m, 0, xColor };
    v[idx++] = { e,  m, 0, xColor };
    v[idx++] = { e, 0, -m, xColor };
    v[idx++] = { e, 0,  m, xColor };
    // +Y marker
    v[idx++] = { -m, e, 0, yColor };
    v[idx++] = {  m, e, 0, yColor };
    v[idx++] = { 0, e, -m, yColor };
    v[idx++] = { 0, e,  m, yColor };
    // +Z marker (top)
    v[idx++] = { -m, 0, 4.7f, zColor };
    v[idx++] = {  m, 0, 4.7f, zColor };
    v[idx++] = { 0, -m, 4.7f, zColor };
    v[idx++] = { 0,  m, 4.7f, zColor };

    // Grid lines
    const uint32_t lineColor = 0xff404040;
    for (float g = -extent; g <= extent + 0.001f; g += step)
    {
        v[idx++] = { -extent, g, 0, lineColor };
        v[idx++] = {  extent, g, 0, lineColor };
        v[idx++] = { g, -extent, 0, lineColor };
        v[idx++] = { g,  extent, 0, lineColor };
    }

    float identity[16];
    bx::mtxIdentity(identity);
    bgfx::setTransform(identity);
    bgfx::setState(BGFX_STATE_WRITE_RGB | BGFX_STATE_PT_LINES);
    bgfx::setVertexBuffer(0, &tvb);

    if (bgfx::isValid(m_colorProgram))
        bgfx::submit(0, m_colorProgram);
    else
        bgfx::discard();
}

void BgfxRenderer::renderFixtures()
{
    static const float selectColor[4] = { 1.0f, 1.0f, 1.0f, 1.0f };  // white highlight

    for (const auto& fixture : m_fixtures)
    {
        // Determine color: highlight if selected (and solid, not ghost)
        const float *color = fixture.color;
        if (m_selectedFixtureId >= 0
            && fixture.id == uint32_t(m_selectedFixtureId)
            && fixture.color[3] >= 0.99f)
        {
            color = selectColor;
        }

        // If fixture has a GDTF scene graph, render hierarchically
        if (fixture.sceneGraph && fixture.sceneGraph->valid)
        {
            renderSceneGraph(fixture.sceneGraph->root, fixture.transform, color);
            continue;
        }

        // Legacy single-mesh path (QXF fixtures)
        const LoadedMesh *mesh = nullptr;
        const char *meshFile = MeshLoader::meshFileForFixtureType(fixture.fixtureType);
        if (meshFile && !m_meshBasePath.empty())
        {
            std::string fullPath = m_meshBasePath + meshFile;
            mesh = m_meshLoader.getMesh(fullPath);
        }

        bool useLitShader = false;

        if (mesh && mesh->isValid())
        {
            bgfx::setTransform(fixture.transform);
            bgfx::setVertexBuffer(0, mesh->vbh);
            bgfx::setIndexBuffer(mesh->ibh);
            useLitShader = true;
        }
        else
        {
            // Fallback: use GDTF primitive based on fixture type
            int primType = 1; // PrimitiveCube default
            switch (fixture.fixtureType)
            {
            case 6:  // Laser
            case 0:  // ColorChanger
            case 1:  // Dimmer
                primType = 8; // PrimitiveConventional (cylinder)
                break;
            case 2:  // Effect
            case 3:  // Fan
            case 4:  // Flower
            case 10: // Other
                primType = 1; // PrimitiveCube
                break;
            }
            const LoadedMesh *prim = m_primitiveGen.getPrimitive(primType);
            if (prim && prim->isValid())
            {
                bgfx::setTransform(fixture.transform);
                bgfx::setVertexBuffer(0, prim->vbh);
                bgfx::setIndexBuffer(prim->ibh);
                useLitShader = true;
            }
            else
            {
                continue;
            }
        }

        bgfx::setUniform(m_u_color, color);

        uint64_t state = BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A
                         | BGFX_STATE_WRITE_Z | BGFX_STATE_DEPTH_TEST_LESS;
        if (color[3] < 0.99f)
            state |= BGFX_STATE_BLEND_ALPHA;

        bgfx::setState(state);

        bgfx::ProgramHandle prog = (useLitShader && bgfx::isValid(m_litProgram))
            ? m_litProgram : m_colorProgram;

        if (bgfx::isValid(prog))
            bgfx::submit(0, prog);
        else
            bgfx::discard();
    }
}

void BgfxRenderer::renderSceneGraph(const SceneNode &node,
                                     const float parentTransform[16],
                                     const float color[4])
{
    // Compute world transform: parent * local
    float worldTransform[16];
    bx::mtxMul(worldTransform, node.localTransform, parentTransform);

    // Render this node's mesh if it has one
    if (node.mesh && node.mesh->isValid())
    {
        bgfx::setTransform(worldTransform);
        bgfx::setVertexBuffer(0, node.mesh->vbh);
        bgfx::setIndexBuffer(node.mesh->ibh);
        bgfx::setUniform(m_u_color, color);

        uint64_t state = BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A
                         | BGFX_STATE_WRITE_Z | BGFX_STATE_DEPTH_TEST_LESS;
        if (color[3] < 0.99f)
            state |= BGFX_STATE_BLEND_ALPHA;
        bgfx::setState(state);

        if (bgfx::isValid(m_litProgram))
            bgfx::submit(0, m_litProgram);
        else
            bgfx::discard();
    }

    // Recurse into children
    for (const auto &child : node.children)
        renderSceneGraph(child, worldTransform, color);
}

void BgfxRenderer::setCalibrationOverlays(const std::vector<RenderEllipsoid>& ellipsoids)
{
    m_ellipsoids = ellipsoids;
}

void BgfxRenderer::renderEllipsoids()
{
    if (m_ellipsoids.empty() || !bgfx::isValid(m_sphereVbh) || !bgfx::isValid(m_litProgram))
        return;

    for (const auto& ell : m_ellipsoids)
    {
        // Build transform: T(center) * R(eigenvectors) * S(semiAxes)
        // Semi-axes are in meters (already converted from cm in SpatialView)

        // Scale matrix
        float scale[16];
        bx::mtxIdentity(scale);
        scale[0]  = ell.semiAxes[0];
        scale[5]  = ell.semiAxes[1];
        scale[10] = ell.semiAxes[2];

        // Rotation matrix from eigenvectors (row-major 3x3 → column-major 4x4)
        float rot[16];
        bx::mtxIdentity(rot);
        rot[0]  = ell.rotation[0]; rot[1]  = ell.rotation[3]; rot[2]  = ell.rotation[6];
        rot[4]  = ell.rotation[1]; rot[5]  = ell.rotation[4]; rot[6]  = ell.rotation[7];
        rot[8]  = ell.rotation[2]; rot[9]  = ell.rotation[5]; rot[10] = ell.rotation[8];

        // Translation
        float trans[16];
        bx::mtxTranslate(trans, ell.center[0], ell.center[1], ell.center[2]);

        // Compose: T * R * S
        float rs[16], model[16];
        bx::mtxMul(rs, scale, rot);
        bx::mtxMul(model, rs, trans);

        bgfx::setTransform(model);
        bgfx::setVertexBuffer(0, m_sphereVbh);
        bgfx::setIndexBuffer(m_sphereIbh);
        bgfx::setUniform(m_u_color, ell.color);

        // Alpha blend: src_alpha, inv_src_alpha. Depth test on, depth write off.
        bgfx::setState(
            BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A
            | BGFX_STATE_DEPTH_TEST_LESS
            | BGFX_STATE_BLEND_ALPHA
            | BGFX_STATE_CULL_CW  // back-face culling for sphere
        );

        bgfx::submit(0, m_litProgram);
    }
}

void BgfxRenderer::renderGizmo()
{
    if (m_selectedFixtureId < 0 || !bgfx::isValid(m_colorProgram))
        return;

    // Find the selected fixture's position for gizmo placement
    for (const auto &f : m_fixtures)
    {
        if (f.id == uint32_t(m_selectedFixtureId) && f.color[3] >= 0.99f)
        {
            m_gizmo.setPosition(f.transform[12], f.transform[13], f.transform[14]);
            m_gizmo.setCameraDistance(m_camera.distance());
            break;
        }
    }

    float pos[3];
    m_gizmo.getPosition(pos);
    float s = m_gizmo.scale();

    // Each arrow: 2 verts for shaft line + 6 verts for arrowhead (2 triangles as a diamond)
    // 3 axes × (2 + 6) = 24 verts for lines, but let's use triangles for arrowheads
    // Simpler approach: draw each arrow as thick lines for shaft + a triangle fan for the cone.
    // Simplest: shaft as 2 lines, arrowhead as a flat diamond (4 triangles = 12 verts)
    // Total: 3 axes × (2 shaft + 12 cone) = 42 verts

    const uint32_t shaftVerts = 6;   // 3 axes × 2 verts
    const uint32_t coneVerts = 36;   // 3 axes × 12 verts (4 triangles each)
    const uint32_t totalVerts = shaftVerts + coneVerts;

    if (!bgfx::getAvailTransientVertexBuffer(totalVerts, PosColorVertex::layout))
        return;

    bgfx::TransientVertexBuffer tvb;
    bgfx::allocTransientVertexBuffer(&tvb, totalVerts, PosColorVertex::layout);
    auto *v = (PosColorVertex *)tvb.data;
    uint32_t idx = 0;

    struct AxisInfo {
        GizmoAxis axis;
        float dir[3];
        uint32_t color;
        uint32_t highlightColor;
    };

    AxisInfo axes[3] = {
        { GizmoAxis::X, {1, 0, 0}, 0xff0000cc, 0xff0000ff },  // red (ABGR)
        { GizmoAxis::Y, {0, 1, 0}, 0xff00cc00, 0xff00ff00 },  // green
        { GizmoAxis::Z, {0, 0, 1}, 0xffcc0000, 0xffff0000 },  // blue
    };

    GizmoAxis active = m_gizmo.activeAxis();
    GizmoAxis hovered = m_gizmo.hoveredAxis();

    for (const auto &a : axes)
    {
        bool highlight = (a.axis == active || a.axis == hovered);
        uint32_t col = highlight ? a.highlightColor : a.color;

        float shaftLen = TranslateGizmo::kShaftLength * s;
        float headLen = TranslateGizmo::kHeadLength * s;
        float headRad = TranslateGizmo::kHeadRadius * s;

        // Shaft: from center to shaft end
        float tipBase[3] = {
            pos[0] + a.dir[0] * shaftLen,
            pos[1] + a.dir[1] * shaftLen,
            pos[2] + a.dir[2] * shaftLen,
        };
        float tip[3] = {
            pos[0] + a.dir[0] * (shaftLen + headLen),
            pos[1] + a.dir[1] * (shaftLen + headLen),
            pos[2] + a.dir[2] * (shaftLen + headLen),
        };

        // Shaft line
        v[idx++] = { pos[0], pos[1], pos[2], col };
        v[idx++] = { tipBase[0], tipBase[1], tipBase[2], col };

        // Arrowhead: 4 triangles forming a diamond/pyramid
        // Need two perpendicular vectors to the axis direction
        float perp1[3], perp2[3];
        if (std::abs(a.dir[2]) < 0.9f)
        {
            // cross with Z
            perp1[0] = -a.dir[1]; perp1[1] = a.dir[0]; perp1[2] = 0;
        }
        else
        {
            // cross with X
            perp1[0] = 0; perp1[1] = -a.dir[2]; perp1[2] = a.dir[1];
        }
        float len = std::sqrt(perp1[0]*perp1[0] + perp1[1]*perp1[1] + perp1[2]*perp1[2]);
        if (len > 1e-6f) { perp1[0] /= len; perp1[1] /= len; perp1[2] /= len; }

        // perp2 = dir × perp1
        perp2[0] = a.dir[1]*perp1[2] - a.dir[2]*perp1[1];
        perp2[1] = a.dir[2]*perp1[0] - a.dir[0]*perp1[2];
        perp2[2] = a.dir[0]*perp1[1] - a.dir[1]*perp1[0];

        // 4 base points of the arrowhead
        float bp[4][3];
        for (int i = 0; i < 4; i++)
        {
            float angle = (i * 3.14159f * 0.5f);  // 0, 90, 180, 270 degrees
            float c = std::cos(angle) * headRad;
            float sn = std::sin(angle) * headRad;
            bp[i][0] = tipBase[0] + perp1[0]*c + perp2[0]*sn;
            bp[i][1] = tipBase[1] + perp1[1]*c + perp2[1]*sn;
            bp[i][2] = tipBase[2] + perp1[2]*c + perp2[2]*sn;
        }

        // 4 triangles: tip → base[i] → base[i+1]
        for (int i = 0; i < 4; i++)
        {
            int j = (i + 1) % 4;
            v[idx++] = { tip[0], tip[1], tip[2], col };
            v[idx++] = { bp[i][0], bp[i][1], bp[i][2], col };
            v[idx++] = { bp[j][0], bp[j][1], bp[j][2], col };
        }
    }

    // Draw shafts as lines
    float identity[16];
    bx::mtxIdentity(identity);
    bgfx::setTransform(identity);

    // Render shaft lines (first 6 verts)
    bgfx::setState(BGFX_STATE_WRITE_RGB | BGFX_STATE_PT_LINES);
    bgfx::setVertexBuffer(0, &tvb, 0, shaftVerts);
    bgfx::submit(0, m_colorProgram);

    // Render arrowhead triangles (remaining verts) — no depth test so gizmo is always on top
    bgfx::setState(BGFX_STATE_WRITE_RGB | BGFX_STATE_WRITE_A | BGFX_STATE_WRITE_Z);
    bgfx::setVertexBuffer(0, &tvb, shaftVerts, coneVerts);
    bgfx::submit(0, m_colorProgram);
}

// --- Factory ---

SpatialRenderer *createBgfxRenderer()
{
    return new BgfxRenderer();
}

} // namespace qlcrender
